---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: 알려진 제한 사항은 이 제품 릴리스에서 지원되지 않거나 제대로 상호 운용되지 않는 플랫폼, 장치 또는 기능을 나타냅니다. 이러한 제한 사항을 주의 깊게 검토하십시오. 
---
= 모든 클라우드 공급자의 Cloud Volumes ONTAP에 대해 알려진 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 이 제품 릴리스에서 지원되지 않거나 제대로 상호 운용되지 않는 플랫폼, 장치 또는 기능을 나타냅니다. 이러한 제한 사항을 주의 깊게 검토하십시오.

다음 제한 사항은 AWS, Azure 및 Google Cloud를 포함한 모든 클라우드 공급자의 Cloud Volumes ONTAP에 적용됩니다.



== 지원되지 않는 ONTAP 기능

Cloud Volumes ONTAP에서는 다음 기능이 지원되지 않습니다.

* 애그리게이트 레벨 인라인 중복제거
* 애그리게이트 레벨 백그라운드 중복제거
* 디스크 유지 관리 센터
* 디스크 삭제
* FabricPool 미러링
* Fibre Channel(FC)
* Flash Pool
* Infinite Volume
* 인터페이스 그룹
* 노드 내 LIF 페일오버
* MetroCluster
* 다중 관리자 검증
+
Cloud Volumes ONTAP에서 다중 관리자 검증을 활성화하면 지원되지 않는 구성이 됩니다.

* RAID4, RAID-DP, RAID-TEC(RAID0 지원)
* Service Processor
* SnapLock Compliance 및 Enterprise 모드(Cloud WORM만 지원)
* SnapMirror 동기식
* VLAN
* SMB Continuous Availability(CA)
+
무중단 운영을 위한 https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["지속적으로 사용 가능한 SMB 공유"^]은(는) 지원되지 않습니다.





== 최대 동시 복제 작업

인스턴스 유형이나 머신 유형에 관계없이 Cloud Volumes ONTAP의 노드당 최대 동시 SnapMirror 또는 SnapVault 전송 수는 100개입니다.



== 클라우드 공급자 스냅샷은 백업 및 복구 계획에 사용해서는 안 됩니다

Cloud Volumes ONTAP 데이터의 백업 및 복구 계획에 클라우드 공급자의 스냅샷을 사용해서는 안 됩니다. Cloud Volumes ONTAP에서 호스팅되는 데이터를 백업 및 복원하려면 항상 ONTAP 스냅샷 복사본 또는 타사 백업 솔루션을 사용해야 합니다.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["NetApp Backup and Recovery를 사용하여 ONTAP 데이터를 백업하고 복원하는 방법을 알아보세요"^].


NOTE: WAFL 파일 시스템의 ONTAP 정합성 시점은 데이터 정합성을 결정합니다. ONTAP만 WAFL 파일 시스템을 중지하여 충돌 시에도 정합성 보장 백업을 생성할 수 있습니다.



== Cloud Volumes ONTAP는 예약형 및 주문형 VM 인스턴스만 지원합니다.

Cloud Volumes ONTAP는 클라우드 공급자가 제공하는 예약 또는 주문형 VM 인스턴스에서 실행할 수 있습니다. 다른 유형의 VM 인스턴스는 지원되지 않습니다.



== 자동 애플리케이션 리소스 관리 솔루션은 사용해서는 안 됩니다

자동 애플리케이션 리소스 관리 솔루션은 Cloud Volumes ONTAP 시스템을 관리해서는 안 됩니다. 관리할 경우 지원되지 않는 구성으로 변경될 수 있습니다. 예를 들어, 솔루션이 Cloud Volumes ONTAP를 지원되지 않는 VM 인스턴스 유형으로 변경할 수 있습니다.



== 소프트웨어 업데이트는 NetApp Console을 통해 완료해야 합니다.

Cloud Volumes ONTAP 업그레이드는 NetApp Console에서 완료해야 합니다. System Manager 또는 CLI를 사용하여 Cloud Volumes ONTAP을 업그레이드하지 마십시오. 이렇게 하면 시스템 안정성에 영향을 미칠 수 있습니다.



== Cloud Volumes ONTAP 배포는 클라우드 공급자의 콘솔에서 수정해서는 안 됩니다

클라우드 공급자 콘솔에서 Cloud Volumes ONTAP 구성을 변경하면 지원되지 않는 구성이 됩니다. NetApp Console에서 생성 및 관리하는 Cloud Volumes ONTAP 리소스를 변경하면 시스템 안정성과 NetApp Console의 시스템 관리 기능에 영향을 미칠 수 있습니다.


NOTE: 초기 배포 후 Cloud Volumes ONTAP 리소스에 사용되는 Azure 구독 이름을 수정할 수 있습니다.



== 디스크와 애그리게이트는 NetApp Console에서 관리해야 합니다.

모든 디스크와 애그리게이트는 Console에서 직접 생성 및 삭제해야 합니다. 다른 관리 툴에서 이러한 작업을 수행해서는 안 됩니다. 그렇게 할 경우 시스템 안정성에 영향을 미치고, 향후 디스크 추가 기능을 저해하며, 클라우드 공급자에게 불필요한 요금이 발생할 수 있습니다.



== SnapManager 라이센스 제한 사항

SnapManager 서버별 라이센스는 Cloud Volumes ONTAP에서 지원됩니다. 스토리지 시스템별(SnapManager 제품군) 라이센스는 지원되지 않습니다.



== 타사 에이전트 및 확장 기능의 제한 사항

Cloud Volumes ONTAP 가상 머신 인스턴스에서는 타사 에이전트 및 VM 확장 기능이 지원되지 않습니다.
