---
sidebar: sidebar 
permalink: reference-configs-gcp.html 
keywords: google, gcp, google cloud platform, explore, standard, premium, byol, paygo, disks, supported, capacity, machine types, sizes, HA, high availability, HA pairs 
summary: Google Cloud에서는 여러 Cloud Volumes ONTAP 구성이 지원됩니다. 
---
= Google Cloud에서 Cloud Volumes ONTAP에 대해 지원되는 구성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud에서는 여러 Cloud Volumes ONTAP 구성이 지원됩니다.



== 라이센스별 지원되는 구성

Cloud Volumes ONTAP는 Google Cloud에서 단일 노드 시스템과 내결함성 및 중단 없는 운영을 위한 고가용성(HA) 노드 쌍으로 제공됩니다.

단일 노드 시스템을 HA 쌍으로 업그레이드하는 것은 지원되지 않습니다. 단일 노드 시스템과 HA 쌍 간에 전환하려면 새 시스템을 배포하고 기존 시스템의 데이터를 새 시스템으로 복제해야 합니다.

Cloud Volumes ONTAP는 클라우드 공급자의 예약 또는 주문형 VM 인스턴스에서 실행할 수 있습니다. 다른 유형의 VM 인스턴스를 사용하는 솔루션은 지원되지 않습니다.

[role="tabbed-block"]
====
.용량 기반 라이센스
--
[cols="h,d,d,d"]
|===
|  | 프리미엄 | 최적화된 ^4^ | 용량 기반 라이센스(Essentials 및 Professional) 


| 최대 시스템 용량(디스크 + 오브젝트 스토리지) | 500 GiB  a| 
용량 기반 라이센스를 사용하는 각 Cloud Volumes ONTAP 시스템은 오브젝트 스토리지로의 계층화를 지원합니다. 계층화된 총 용량은 클라우드 공급자의 버킷 제한까지 확장할 수 있습니다. 라이센스는 용량 제한을 적용하지 않지만 계층화를 구성하고 관리할 때 최적의 성능, 안정성 및 비용 효율성을 보장하기 위해 https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["FabricPool 모범 사례"^]를 따라야 합니다.



| 지원되는 시스템 유형 ^1^  a| 
* n1-standard-8 ^1^
* n1-standard-32 ^1^
* n2-standard-4
* n2-standard-8
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64

 a| 
* n2-standard-4
* n2-standard-8

 a| 
* n1-standard-8 ^1^
* n1-standard-32 ^1^
* n2-standard-4
* n2-standard-8
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64




| 지원되는 디스크 유형 ^2^ 3+| 균형형 영구 디스크 ^3^, 성능(SSD) 영구 디스크 ^3^ 및 표준(HDD) 영구 디스크. 
|===
참고:

. ^1^ n1 시리즈 장비는 Google Cloud에 Cloud Volumes ONTAP의 새 인스턴스를 배포할 때 NetApp Console에서 더 이상 선택할 수 없습니다. n1 시리즈 장비는 기존 시스템에서만 유지 및 지원됩니다. Cloud Volumes ONTAP의 새 배포는 9.8 릴리스부터 Google Cloud에서 지원됩니다. Cloud Volumes ONTAP 9.8 이상 버전과 호환되는 n2 시리즈 장비로 전환하는 것이 좋습니다. 단, API를 통한 새 배포에는 n1 시리즈 장비를 사용할 수 있습니다.
+
custom-4-16384 머신 유형은 더 이상 새로운 Cloud Volumes ONTAP 시스템에서 지원되지 않습니다. 이 머신 유형에서 실행 중인 기존 시스템이 있는 경우 계속 사용할 수 있지만 n2-standard-4 머신 유형으로 전환하는 것이 좋습니다.

. ^2^ 디스크 제한으로 인해 디스크만 사용하여 최대 시스템 용량 제한에 도달하지 못할 수 있습니다.  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["비활성 데이터를 오브젝트 스토리지로 계층화"^]를 통해 용량 제한에 도달할 수 있습니다.
+
link:reference-limits-gcp.html["Google Cloud의 디스크 제한에 대해 자세히 알아보십시오"].

. ^3^ 균형형 영구 디스크와 성능(SSD) 영구 디스크를 사용할 때 향상된 쓰기 성능이 활성화됩니다.
+
Cloud Volumes ONTAP 9.13.0부터 _Flash Cache_, 높은 쓰기 속도 및 8,896바이트의 더 높은 최대 전송 단위(MTU)를 다음 HA 쌍 구축 인스턴스에 사용할 수 있습니다.

+
** n2-standard-16
** n2-standard-32
** n2-standard-48
** n2-standard-64
+
적합한 인스턴스 유형을 배포할 때 _Flash Cache_와 빠른 쓰기 속도를 활성화할 수 있습니다. 최대 전송 단위 8,896바이트를 활성화하려면 배포 시 VPC-1, VPC-2 또는 VPC-3을 선택해야 합니다. MTU가 높을수록 네트워크 처리량이 향상됩니다. 이러한 배포를 시작하는 방법에 대한 자세한 내용은 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["Google Cloud에서 HA 쌍 시작"]을 참조하십시오.

+

NOTE: _Flash cache_, 높은 쓰기 모드 및 8,896의 MTU는 기능에 따라 달라지며 구성된 인스턴스 내에서 개별적으로 비활성화할 수 없습니다.



. ^4^ 2025년 8월 11일부터 Cloud Volumes ONTAP Optimized 라이센스는 더 이상 사용되지 않으며 Google Cloud 마켓플레이스에서 종량제(PAYGO) 구독으로 구매 또는 갱신할 수 없습니다. 자세한 내용은 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAP의 새로운 기능"^]를 참조하십시오.


--
.노드 기반 라이센스
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO Explore | PAYGO Standard | PAYGO Premium | 노드 기반 BYOL 


| 최대 시스템 용량(디스크 + 오브젝트 스토리지) | 2TB ^2^ | 10TiB | 368TiB | 라이선스당 368 TiB 


| 지원되는 시스템 유형 ^3^  a| 
* n2-standard-4

 a| 
* n1-standard-8 ^3^
* n2-standard-8

 a| 
* n1-standard-32 ^3^
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64

 a| 
* n1-standard-8 ^3^
* n1-standard-32 ^3^
* n2-standard-4
* n2-standard-8
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64




| 지원되는 디스크 유형 4+| 균형형 영구 디스크 ^4^, 성능(SSD) 영구 디스크 ^4^ 및 표준(HDD) 영구 디스크. 
|===
참고:

. ^1^ 디스크 제한으로 인해 디스크만으로는 시스템 최대 용량 제한에 도달하지 못할 수 있습니다. 용량 제한에 도달하는 방법은 다음과 같습니다 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["비활성 데이터를 오브젝트 스토리지로 계층화"^].
+
link:reference-limits-gcp.html["Google Cloud의 디스크 제한에 대해 자세히 알아보십시오"].

. ^2^ Google Cloud Storage로의 데이터 계층화는 PAYGO Explore에서 지원되지 않습니다.
. ^3^ Google Cloud에서 Cloud Volumes ONTAP의 새 인스턴스를 배포할 때 Console에서 n1 시리즈 머신을 더 이상 선택할 수 없습니다. n1 시리즈 머신은 기존 시스템에서만 유지 및 지원됩니다. Cloud Volumes ONTAP의 새 배포는 9.8 릴리스부터 Google Cloud에서만 지원됩니다. Cloud Volumes ONTAP 9.8 이상 버전과 호환되는 n2 시리즈 머신으로 전환하는 것이 좋습니다. 단, API를 통한 새 배포에는 n1 시리즈 머신을 계속 사용할 수 있습니다.
+
custom-4-16384 머신 유형은 더 이상 새로운 Cloud Volumes ONTAP 시스템에서 지원되지 않습니다. 이 머신 유형에서 실행 중인 기존 시스템이 있는 경우 계속 사용할 수 있지만 n2-standard-4 머신 유형으로 전환하는 것이 좋습니다.

. ^4^ 균형형 영구 디스크와 성능(SSD) 영구 디스크를 사용할 때 쓰기 성능 향상이 활성화됩니다.


Console에 Standard 및 BYOL에 대해 지원되는 추가 머신 유형인 n1-highmem-4가 표시됩니다. 그러나 이 머신 유형은 운영 환경에 적합하지 않습니다. 특정 연구실 환경에서만 사용할 수 있도록 제공됩니다.

Cloud Volumes ONTAP 소프트웨어 버전 9.13.0부터 _Flash Cache_, 빠른 쓰기 속도, 그리고 8,896바이트의 더 높은 최대 전송 단위(MTU)가 다음 HA 페어 배포 인스턴스에서 사용 가능합니다:

* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64


적합한 인스턴스 유형을 배포할 때 _Flash Cache_와 빠른 쓰기 속도를 활성화할 수 있습니다. 최대 전송 단위 8,896바이트를 활성화하려면 배포 시 VPC-1, VPC-2 또는 VPC-3을 선택해야 합니다. MTU가 높을수록 네트워크 처리량이 향상됩니다. 이러한 배포를 시작하는 방법에 대한 자세한 내용은 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["Google Cloud에서 HA 쌍 시작"]을 참조하십시오.


NOTE: _Flash cache_, 높은 쓰기 모드 및 8,896의 MTU는 기능에 따라 달라지며 구성된 인스턴스 내에서 개별적으로 비활성화할 수 없습니다.

--
====
특정 머신 유형에 대한 자세한 내용은 Google Cloud 설명서를 참조하십시오.

* https://cloud.google.com/compute/docs/general-purpose-machines#n1_machines["n1 시리즈 범용 머신 유형"^]
* https://cloud.google.com/compute/docs/general-purpose-machines#n2_series["N2 시리즈 범용 시스템 유형"^]




== 지원되는 디스크 크기

Google Cloud에서 애그리게이트는 동일한 유형과 크기의 디스크를 최대 6개까지 포함할 수 있습니다. 지원되는 디스크 크기는 다음과 같습니다.

* 100 GB
* 500 GB
* 1 TB
* 2TB
* 4TB
* 8TB
* 16TB
* 64 TB




== 지원되는 지역

Google Cloud 지역 지원에 대한 자세한 내용은 https://bluexp.netapp.com/cloud-volumes-global-regions["Cloud Volumes 글로벌 지역"^]를 참조하십시오.
